### PR TITLE
#5 - fixed category.map is not a function error

### LINKED ISSUE #5: (SP: 0.5) (My Resources) fix category.map is not a function error
fix category.map is not a function error, which appears after trying to filter question resource by category:

image

### PR DESCRIPTION
**Pull request by melyasanya**
Fixed bug with category map by changing if check. Now we are checking if category is an array

### CODE REVIEW

**Review by natamrshn — APPROVED** [review]

**Comment by melyasanya** [comment]
With the fix, new bug appears, when it is impossible to choose none categories. My guess is that the functionality of choosing none category hasn't already been made, but I may be wrong and this is just another bug

**Review by lsofiabo — APPROVED** [review]

**Review by VoitV — APPROVED** [review]

File: src/utils/getCategoriesOption.js [hunk 1]
```diff
@@ -1,8 +1,10 @@
 const getCategoriesOptions = (categories) => {
-  if (categories) {
+  if (Array.isArray(categories)) {
     return categories.map((item) => (item === 'null' ? null : item))
```
Comment (nadraharr) [inline src/utils/getCategoriesOption.js:3]: Maybe it would be more logical to put this code inside of "if (categories)" block. But this version should work anyway.

**Review by nadraharr — APPROVED** [review]

File: src/utils/getCategoriesOption.js
Comment (vlad-khrychov) [inline src/utils/getCategoriesOption.js:1]: Do you think it might be better to always return an array? I'm talking about the 6th line, if we get a single category, we can return an array with that category, like `[categories]`.

**Review by vlad-khrychov — APPROVED** [review]

File: src/utils/getCategoriesOption.js
Comment (melyasanya) [reply src/utils/getCategoriesOption.js:1]: Result is the same, but logically I agree with, it should better return array

File: src/utils/getCategoriesOption.js (hunk 1 above)
Comment (melyasanya) [reply src/utils/getCategoriesOption.js:3]: the problem is that categories can sometimes be string, and mapping string is impossible, so i need to check if categories is array to map it

**Comment by melyasanya** [comment]
In the process of fixing this bug, anothe bug appeared. It was impossible to pick none category, because when choosing none it returns null as string, not as null, so i changed it and added logic to getMatchOptions, so code will be looking for nulls in categories in database
